language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_script:
  - cd py-version
  - python main.py &
  - SERVER_PYTHON_PID=$!
  - echo Python Micro HTTP Server\'s PID $SERVER_PYTHON_PID
  - cd ../c-version
  - make clean; make
  - ./microhttpserver &
  - SERVER_C_PID=$!
  - echo C Micro HTTP Server\'s PID $SERVER_C_PID
  - cd ..
script:
  - python autotest/client.py localhost:8000
  - kill $SERVER_PYTHON_PID
  - python autotest/client.py localhost:8001
  - kill $SERVER_C_PID
